version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./api:/app/api

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
